<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="ScholarwaveCBTApp">
      <HintPath>..\..\bin\Debug\net10.0-windows\Scholarwave CBT App.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
